### PR TITLE
NoteApp : Modified the color palette, added Poppins Font, and convert…

### PR DESCRIPTION
**Pull request by Krish-Parekh**
…ed edit-text to outlined-edit-text.

### CODE REVIEW

**Review by avidraghav — CHANGES_REQUESTED** [review]
The font files together add over 600 kB to project size, please either choose some files with less size or apply less fonts styles.

**Comment by Krish-Parekh** [comment]
Cool I will work on that

**Comment by avidraghav** [comment]
Please take a pull from master for any changes.

**Comment by Krish-Parekh** [comment]
Hey @avidraghav  I have removed one font style which has reduced the file size to 458kb,  would that be fine ?

**Comment by avidraghav** [comment]
You added 4 font resource files each of 150 KB. Which files did you removed?

**Comment by Krish-Parekh** [comment]
I have removed the Poppins Light,

**Comment by avidraghav** [comment]
Ok.

**Comment by Krish-Parekh** [comment]
Hey @avidraghav can I change the app demo gif in the readme.md file ?

**Comment by avidraghav** [comment]
Sure, that would be great :)

**Comment by avidraghav** [comment]
Push the Readme changes in this branch itself

**Comment by avidraghav** [comment]
Please make the PR ready for review once all changes have been done from your side

**Comment by avidraghav** [comment]
Thanks and Kudos for making impactful contribution to MyNotes, I hope you gained some knowledge about Open-Source development. Do share your contribution on Twitter by tagging me at @avidraghav
Congratulations again 🎊 😄

**Pull request merged**
