### PR TITLE
Dependencies and AGP upgraded

### PR DESCRIPTION
**Pull request by RumitPatel**
- All dependencies updated.
- Android gradle plugin upgraded to "8.0.2"

### CODE REVIEW

**Comment by avidraghav** [comment]
Thanks for the PR @RumitPatel, I'll review it in detail but currently CI workflow is failing, can u please see rectify the issues?

**Comment by EmedStoreIT** [comment]
Sure @avidraghav , I'll check once I get time.

**Comment by RumitPatel** [comment]
Sure @avidraghav , I will check it once I get time.

**Comment by EmedStoreIT** [comment]
@avidraghav You can review. CI workflow does not fail now.

**Comment by RumitPatel** [comment]
@avidraghav  You can review. CI workflow does not fail now.

**Comment by avidraghav** [comment]
it's still failing, the issue has arisen due to update of some dependency i guess. Closing the PR for now. If you resolve the issue reopen it.

**Pull request closed without merging**
