### PR TITLE
Rahul raghuwanshi/UI improvement

### PR DESCRIPTION
**Pull request by thisrahul**
improve recyclerview item layout

### CODE REVIEW

**Comment by avidraghav** [comment]
Can you attach the screenshot or a screen recording of the new UI?

**Comment by thisrahul** [comment]
Here is a video 


https://user-images.githubusercontent.com/52368582/194605629-fd904b30-e698-45b4-ae88-60dbff1db35a.mp4

**Comment by avidraghav** [comment]
Thanks and Kudos for making another contribution to MyNotes!
I'll be sharing yours and others contribution on Twitter and LinkedIn shortly. If you like do connect with me at @avidraghav on both Twitter and LinkedIn

**Comment by thisrahul** [comment]
Actually i am not on twitter but on linkedin i start following you

**Comment by thisrahul** [comment]
And also can you please label my pr's with hacktoberfest accepted

**Pull request merged**
