### PR TITLE
Rahul raghuwanshi/navigation animation

### PR DESCRIPTION
**Pull request by thisrahul**
Add animation
1.Entry animation for recyclerview
2.recyclerview item click to detailadd fragment animation
3.add btn to add fragment animation

### CODE REVIEW

**Review by avidraghav — COMMENTED** [review]
The newly added functions are always added in the last of the file. Please refactor the code.
Apologies for the late review.

**Comment by thisrahul** [comment]
Okay will fix this

**Comment by avidraghav** [comment]
Please apply the changes as suggested so that I can merge the PR :)

**Comment by thisrahul** [comment]
yes sir currently working on it .

**Comment by thisrahul** [comment]
Sir i need to confirm like for 3rd point its already have animation from right to left when note is saved
https://user-images.githubusercontent.com/52368582/193991029-e3994859-8ce0-44db-bf10-92cd0ebbf358.mp4

**Comment by avidraghav** [comment]
Yeah my bad please make it from Left to right.

**Comment by thisrahul** [comment]
Hello sir, i replace recyclerview entry animation because i find this appropriate please check and also check the fix when note is save left to right animation 

https://user-images.githubusercontent.com/52368582/194007505-ce2f27ec-c0d2-4399-8b20-bd150ea04867.mp4

**Comment by avidraghav** [comment]
Yeah this looks good too, just make sure that the recyclerview animation only happens when the app is launched and not everytime a user navigates back to AllTasksFragment.

**Comment by thisrahul** [comment]
Yes but it happen two time like when user first time launch the app and when note is save then come to all fragment because it destroy and create new thats why

**Comment by avidraghav** [comment]
Tip to achieve this: The app has single activity architecture. Both fragments are associated with the Same Activity. Therefore the activity's onCreate() is the one that gets called only once throughout the app session. 
Think about this and use it to implement the desired behavior.

**Comment by thisrahul** [comment]
Okay thank you

**Comment by thisrahul** [comment]
changes done

**Review by avidraghav — CHANGES_REQUESTED** [review]
Please delete the animation resource file(s) which are not used anymore.

**Comment by thisrahul** [comment]
deleted

**Review by avidraghav — APPROVED** [review]

**Comment by avidraghav** [comment]
Thanks and Kudos for making impactful contribution to MyNotes, I hope you gained some knowledge about Open-Source development. Do share your contribution on Twitter by tagging me at @avidraghav 
Congratulations again 🎊  😄

**Comment by avidraghav** [comment]
Thanks and Kudos for making impactful contribution to MyNotes, I hope you gained some knowledge about Open-Source development. Do share your contribution on Twitter by tagging me at @avidraghav
Congratulations again 🎊 😄

**Pull request merged**
