### PR TITLE
NoteApp : Modified TaskEntity.kt from Serializable to Parcelable

### PR DESCRIPTION
**Pull request by Krish-Parekh**

### CODE REVIEW

**Comment by Krish-Parekh** [comment]
Hey @avidraghav  I have made the changes if you accept this pull request please label it with hacktober-fest

**Review by avidraghav — CHANGES_REQUESTED** [review]
Please revert the AGP version to `7.2.0`, I got some build errors while using AGP v7.3.0 

Though it's recommended to always use the latest version of dependencies but the latest dependencies are not always the most stable one, saying this from experience.

Also a tip for you: If a developer in the team specifically reverts a dependency update (as I did) then others who are curious about the change should consult with him as why he did that and not override the change without asking :)

**Comment by Krish-Parekh** [comment]
Yes, I'll do that, but if you could kindly clarify why you changed the dependence to a lower version as my end of things is operating just fine, I encountered this issue after switching to a lower version. 

image

**Comment by avidraghav** [comment]
I was getting the error that the project was Incompatible with AGP `7.3.0` hence I couldn't build the project. I'll inspect this and get back to you once I get the time.

**Review by avidraghav — APPROVED** [review]

**Comment by avidraghav** [comment]
Thanks for another contribution to MyNotes 🌟

**Pull request merged**
